### ISSUE TITLE
Adding a landscape reference variable

### ISSUE THREAD

**Issue by g-reese** [SOSIEL/The-SOSIEL-Platform#32]
Has there been any attempt to expand the set of reference landscape variables that the SOSIEL algorithm can analyze and use to choose a Decision Option? If not already completed, would it be possible/difficult to change the code so that output from some other LANDIS-II extension, e.g., wind, fire, could be used to direct the selection of a Decision Option? This could allow testing of, for example, the type and amount of harvesting that should be implemented when targeting impacts from other disturbances.

**Comment by IvanPizhenko** [comment]
Hi @g-reese 

> Has there been any attempt to expand the set of reference landscape variables that the SOSIEL algorithm can analyze and use to choose a Decision Option? 

No, there were no such attempts.

> If not already completed, would it be possible/difficult to change the code so that output from some other LANDIS-II extension, e.g., wind, fire, could be used to direct the selection of a Decision Option?

Extensions are developed by a different people. And if I remember correctly, typically, extension does not expose its data directly to simulator, so it is not possible to easily get that data. Each extensions however, typically, produces some output files, however, again, if I remember correctly, they are produced somewhere in the end, so another extension can't get that data in the middle, when it actually needs it. Fortunately, all this software is open source and permits you modifying it, so with enough will and free time you can get your own reworked versions of extensions and simulator itself, that will make extensions data available to other extensions earlier and easier to discover and reuse. I also wish this could be possible out of the box, but it is not. We made some attempt to use one of extensions, but we had to load it on our own, use reflection to get into internal data structures and so on. Not sure if this code is present now, but there was something like this at some moment in the past.

**Comment by IvanPizhenko** [comment]
Also at the time when I last time was working with LANDIS, it itself & many extensions were stick to quite outdated .NET Core 2 or something like that. I wish we could have it all on latest .NET 8, but I'm not sure if LANDIS & extensions are ported. Again, own ports of LANDIS and necessary extensions can be maintained, because it all is open-source. But that all requires some time, efforts, budget, etc.

**Comment by gsotnik** [comment]
Each iteration, SHE chooses decision options based on the state of the landscape at the end of the previous iteration. SHE accounts in its decision making for all the changes to the landscape made by all the running extensions. SHE does not have access to the calculations made by other extensions until the end of the simulation. As mentioned above, it cannot use that data during a simulation. Unless, of course, the extension is integrated into SHE, which would then give SHE access to the extension's calculations during a simulation. Such integration is not difficult with some advanced programming expertise and time.

**Comment by g-reese** [comment]
Thank you for addressing my questions.
